import random

# print the random integer number - done
# take input from the user
# check weather the input is less then the random number generated by computer
# if less print the message it is less and vice versa
# count how many time user take to guess the number
# loop untill the user guess the number


rand = random.randint(1, 100)
cnt = 0
while True:
    guess = int(input("Guess the number from 1 to 100: "))
    print()
    if guess == rand:
        cnt += 1
        print(f"Hurrey! you won the game\nYour score is {cnt}\n")
        break
    elif guess > rand:
        cnt += 1
        print(
            f"Oops! You have enter higher value\nPlease enter the lower value then {guess}\n"
        )

    elif guess < rand:
        cnt += 1
        print(
            f"Oops! You have enter lower value\nPlease enter the higher value then {guess}\n"
        )
